### ISSUE TITLE
Package doesn't work with Laravel 5.1

### ISSUE THREAD

**Issue by yadakhov** [nWidart/DbExporter#27] opened 2015-08-01 10:24 UTC
Problem 1
    - Installation request for nwidart/db-exporter ^1.0 -> satisfiable by nwidart/db-exporter[1.0].
    - Conclusion: remove laravel/framework v5.1.8
    - Conclusion: don't install laravel/framework v5.1.8
    - nwidart/db-exporter 1.0 requires illuminate/support ~4 -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13,

**Comment by nWidart** [comment] 2015-08-01 16:58
duplicate of #26 

Please use dev-master.

**Closed by nWidart** 2015-08-01 16:58 UTC
