### ISSUE TITLE
[BadMethodCallException] Call to undefined method [package]

### ISSUE THREAD

**Issue by Chopsueyer** [nWidart/DbExporter#26] opened 2015-07-08 17:09 UTC
Hi!

I can't use your the package correctly after install the dev-master version via composer. I always get this error if I try to use it directly or if I try to do your "publish" command ("php artisan config:publish nwidart/db-exporter"):

    [BadMethodCallException]            
    Call to undefined method [package]
    

Any idea to help me?

Thanks

**Comment by nWidart** [comment] 2015-08-01 16:58
Duplicate of #25

**Closed by nWidart** 2015-08-01 16:58 UTC
